In [2]:
from tensorflow.keras.layers import LSTM, Flatten, Dense
from tensorflow.keras.models import Sequential
import tensorflow.keras.backend as K
import numpy as np
import tensorflow as tf
from keras.callbacks import EarlyStopping
import yfinance as yf
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import LSTM, Flatten, Dense
from tensorflow.keras.models import Sequential
import tensorflow.keras.backend as K
from keras.models import load_model,save_model

In [3]:
def get_data(start_date='2014-01-01', end_date='2018-01-01'):
    #def prepair_data(window_x,window_y):
    tickers = ['VTI', 'AGG', 'DBC', 'VIXY']
    
    
    df_list = pd.DataFrame()
    for ticker in tickers:
        data = yf.download(ticker, group_by="Ticker", start=start_date, end=end_date)
        data['ticker'] = ticker
        data = data[['Close','ticker']]
        df_list = pd.concat([df_list,data])
        
    df_pivot = pd.pivot_table(df_list, values='Close',index=df_list.index.values,
                        columns=['ticker'])
    return df_pivot

In [4]:
data = get_data()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [8]:
data.head()

ticker             AGG        DBC         VIXY        VTI
2014-01-02  106.500000  25.290001  2328.800049  95.080002
2014-01-03  106.540001  25.129999  2313.600098  95.059998
2014-01-06  106.680000  25.160000  2284.800049  94.809998
2014-01-07  106.730003  25.139999  2234.399902  95.419998
2014-01-08  106.410004  24.900000  2238.399902  95.489998

In [9]:
def get_return_data(data):
    assets = data.columns
    portfolio_return_data = np.concatenate([data.pct_change().values[1:] ], axis=1)
    portfolio_return_data_df = pd.DataFrame(portfolio_return_data,  columns =assets,index=data.index.values[1:],)  
    return portfolio_return_data_df

In [11]:
return_data = get_return_data(data)
return_data.head()

ticker           AGG       DBC      VIXY       VTI
2014-01-03  0.000376 -0.006327 -0.006527 -0.000210
2014-01-06  0.001314  0.001194 -0.012448 -0.002630
2014-01-07  0.000469 -0.000795 -0.022059  0.006434
2014-01-08 -0.002998 -0.009547  0.001790  0.000734
2014-01-09  0.001410 -0.008032  0.001787  0.000838

In [95]:
    
class Model:
    def __init__(self,timesteps_input=64,timesteps_output=19):
        self.data = None
        self.model = None
        
        self.timesteps_input = timesteps_input
        self.timesteps_output = timesteps_output
        
        
    def build_model(self, input_shape, outputs):
        '''
        Builds and returns the Deep Neural Network that will compute the allocation ratios
        that optimize the Sharpe Ratio of the portfolio
        
        inputs: input_shape - tuple of the input shape, outputs - the number of assets
        returns: a Deep Neural Network model
        '''
        model = Sequential([
            LSTM(64, input_shape=input_shape),
            #Flatten(),
            Dense(outputs, activation='softmax')
        ])

        def sharpe_loss(_, y_pred):
            # make all time-series start at 1
            data = tf.divide(self.data, self.data[0])  

            # value of the portfolio after allocations applied
            portfolio_values = tf.reduce_sum(tf.multiply(data, y_pred), axis=1) 
            
            portfolio_returns = (portfolio_values[1:] - portfolio_values[:-1]) / portfolio_values[:-1] 

            sharpe = (K.mean(portfolio_returns) * 255) / (K.std(portfolio_returns)* np.sqrt(255))
            
            # since we want to maximize Sharpe, while gradient descent minimizes the loss, 
            #   we can negate Sharpe (the min of a negated function is its max)
            return -sharpe
    

        
        model.compile(loss=sharpe_loss, optimizer='adam')
        return model
    
    def train(self,data):
        '''
        Computes and returns the allocation ratios that optimize the Sharpe over the given data
        
        input: data - DataFrame of historical closing prices of various assets
        
        return: the allocations ratios for each of the given assets
        '''
        
        # data with returns
        data_w_ret = np.concatenate([ data.values[1:], data.pct_change().values[1:] ], axis=1)
        tickers = data.columns
        data = data.iloc[1:]
        self.data = tf.cast(tf.constant(data), float)
        
        if self.model is None:
            self.model = self.build_model((None,8), len(data.columns))
        
        fit_predict_data = data_w_ret[np.newaxis,:]        
        self.model.fit(fit_predict_data, np.zeros((1, len(data.columns))), epochs=50, shuffle=False)

In [96]:
model = Model()
train_data = get_data()
model_trained = model.train(train_data)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 0.9310
Epoch 2/50
1/1 [==============================] - 0s 190ms/step - loss: 0.8934
Epoch 3/50
1/1 [==============================] - 0s 180ms/step - loss: 0.8629
Epoch 4/50
1/1 [==============================] - 0s 188ms/step - loss: 0.8393
Epoch 5/50
1/1 [==============================] - 0s 187ms/step - loss: 0.8199
Epoch 6/50
1/1 [==============================] - 0s 193ms/step - loss: 0.8016
Epoch 7/50
1/1 [==============================] - 0s 193ms/step - loss: 0.7821
Epoch 8/50
1/1 [==============================] - 0s 184ms/step - loss: 0.7607
Epoch 9/50
1/1 [==============================] - 0s 181ms/step - loss: 0.7406
Epoch 10/50
1/1 [==============================] - 0s 199ms/step - loss: 0.7248
Epoch 11/50
1/1 [==============================] - 0s 184ms/step - loss: 0.7122
Epoch 12/50
1/1 [==============================] - 0s 182ms/step - loss: 0.7006
Epoch 13/50
1/1 [==============================] - 0s 185ms/step - loss: 0.6885
Epoch 14/50
1/1 [==============================] - 0s 180ms/step - loss: 0.6752
Epoch 15/50
1/1 [==============================] - 0s 199ms/step - loss: 0.6606
Epoch 16/50
1/1 [==============================] - 0s 207ms/step - loss: 0.6445
Epoch 17/50
1/1 [==============================] - 0s 190ms/step - loss: 0.6267
Epoch 18/50
1/1 [==============================] - 0s 208ms/step - loss: 0.6067
Epoch 19/50
1/1 [==============================] - 0s 184ms/step - loss: 0.5837
Epoch 20/50
1/1 [==============================] - 0s 210ms/step - loss: 0.5566
Epoch 21/50
1/1 [==============================] - 0s 201ms/step - loss: 0.5240
Epoch 22/50
1/1 [==============================] - 0s 193ms/step - loss: 0.4842
Epoch 23/50
1/1 [==============================] - 0s 184ms/step - loss: 0.4351
Epoch 24/50
1/1 [==============================] - 0s 181ms/step - loss: 0.3748
Epoch 25/50
1/1 [==============================] - 0s 187ms/step - loss: 0.3021
Epoch 26/50
1/1 [==============================] - 0s 181ms/step - loss: 0.2171
Epoch 27/50
1/1 [==============================] - 0s 225ms/step - loss: 0.1209
Epoch 28/50
1/1 [==============================] - 0s 185ms/step - loss: 0.0155
Epoch 29/50
1/1 [==============================] - 0s 209ms/step - loss: -0.0971
Epoch 30/50
1/1 [==============================] - 0s 190ms/step - loss: -0.2153
Epoch 31/50
1/1 [==============================] - 0s 196ms/step - loss: -0.3366
Epoch 32/50
1/1 [==============================] - 0s 200ms/step - loss: -0.4560
Epoch 33/50
1/1 [==============================] - 0s 187ms/step - loss: -0.5646
Epoch 34/50
1/1 [==============================] - 0s 204ms/step - loss: -0.6515
Epoch 35/50
1/1 [==============================] - 0s 190ms/step - loss: -0.7096
Epoch 36/50
1/1 [==============================] - 0s 186ms/step - loss: -0.7422
Epoch 37/50
1/1 [==============================] - 0s 194ms/step - loss: -0.7602
Epoch 38/50
1/1 [==============================] - 0s 192ms/step - loss: -0.7715
Epoch 39/50
1/1 [==============================] - 0s 186ms/step - loss: -0.7801
Epoch 40/50
1/1 [==============================] - 0s 192ms/step - loss: -0.7871
Epoch 41/50
1/1 [==============================] - 0s 188ms/step - loss: -0.7931
Epoch 42/50
1/1 [==============================] - 0s 181ms/step - loss: -0.7985
Epoch 43/50
1/1 [==============================] - 0s 183ms/step - loss: -0.8033
Epoch 44/50
1/1 [==============================] - 0s 183ms/step - loss: -0.8077
Epoch 45/50
1/1 [==============================] - 0s 185ms/step - loss: -0.8118
Epoch 46/50
1/1 [==============================] - 0s 197ms/step - loss: -0.8155
Epoch 47/50
1/1 [==============================] - 0s 185ms/step - loss: -0.8184
Epoch 48/50
1/1 [==============================] - 0s 207ms/step - loss: -0.8207
Epoch 49/50
1/1 [==============================] - 0s 189ms/step - loss: -0.8226
Epoch 50/50
1/1 [==============================] - 0s 184ms/step - loss: -0.8245

In [97]:
def get_allocations(model,data,allocation_date=None):
    
    # data with returns
    data_w_ret = np.concatenate([ data.values[1:], data.pct_change().values[1:] ], axis=1)
    fit_predict_data = data_w_ret[np.newaxis,:]        
    tickers = data.columns
    df = pd.DataFrame(model.predict(fit_predict_data)[0])
    list_allocations = {}
    for i in range(0,len(tickers)):
        list_allocations[tickers[i]] = df[0][i]
    
    return list_allocations

In [98]:
def portfolio_return(portfolio_prices_data,trained_model):

    portfolio_prices_data = portfolio_prices_data
#    portfolio_prices_data.index = portfolio_prices_data.index.strftime('%Y-%m-%d')

    trained_model = trained_model
    
    allocations = get_allocations(trained_model,portfolio_prices_data)
    assets = portfolio_prices_data.columns
    portfolio_return_data = np.concatenate([portfolio_prices_data.pct_change().values[1:] ], axis=1)
    portfolio_return_data_df = pd.DataFrame(portfolio_return_data,  columns =assets,index=portfolio_prices_data.index.values[1:])  
#    allocations_df = pd.DataFrame(allocations, index=[0])
    portfolio_daily_return_data_df = pd.DataFrame()
    for asset in assets:
        portfolio_daily_return_data_df[asset + ' return'] = portfolio_return_data_df[asset]*allocations[asset]
    portfolio_daily_return_data_df['daily_return'] = portfolio_daily_return_data_df.sum(axis = 1)
    portfolio_daily_return_data_df['cumulative_ret'] = (portfolio_daily_return_data_df['daily_return'] + 1).cumprod()
    return portfolio_daily_return_data_df

In [105]:

start_date = '2018-01-01'
end_date = '2019-10-01'
test_data = get_data(start_date,end_date)
trained_model = load_model('my_model.h5',compile=False)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [104]:
allocations = get_allocations(trained_model,test_data)
allocations_df = pd.DataFrame(allocations, index=[0])
allocations_df.head()

        AGG       DBC     VIXY      VTI
0  0.254807  0.004283  0.00962  0.73129

In [102]:
port_return = portfolio_return(test_data,trained_model)
port_return = port_return.sort_index(ascending=False)

In [103]:
port_return

,AGG return,DBC return,VIXY return,VTI return,daily_return,cumulative_ret
2019-09-30,0.000068,-0.000042,-0.000273,0.003406,0.003158,1.085543
2019-09-27,0.000316,-0.000017,0.000266,-0.004353,-0.003788,1.082126
2019-09-26,0.000429,0.000000,0.000064,-0.002218,-0.001725,1.086241
2019-09-25,-0.001057,-0.000025,-0.000208,0.004610,0.003319,1.088117
2019-09-24,0.000699,-0.000050,0.000446,-0.006778,-0.005682,1.084518
...,...,...,...,...,...,...
2018-01-09,-0.000701,0.000028,0.000098,0.001351,0.000777,1.013115
2018-01-08,-0.000070,-0.000003,-0.000123,0.001667,0.001471,1.012329
2018-01-05,-0.000163,-0.000015,0.000004,0.004297,0.004123,1.010842
2018-01-04,-0.000163,-0.000005,-0.000031,0.002788,0.002589,1.006691
2018-01-03,0.000023,0.000026,-0.000190,0.004233,0.004092,1.004092